version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: npm install
      - run: make style
      - run: make coverage-cli
      - run: make coverage-ui
      - run:
          command: ./node_modules/.bin/codecov
          environment:
            CODECOV_TOKEN: "a1186210-a38e-4e2d-a4e9-87dbe0f1ddde"
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./publish $NPMJS_TOKEN
            fi
