#!/usr/bin/env node
var execSync = require('child_process').execSync
var format = require('util').format
var gt = require('semver').gt
var pkg = require('./package.json')

publish()

function publish () {
    var remoteVersion = '0.0.0'
    try {
        remoteVersion = execSync(format('npm show %s version', pkg.name)).toString().trim() || remoteVersion
    } catch (ex) {}
    if (gt(remoteVersion, pkg.version)) return
    execSync('npm publish --access public')
}
