version: 2.1

docker: &image
  - image: gmathieu/node-browsers:3.0.0

commands:
  install:
    steps:
      - checkout
      - run: yarn install --frozen-lockfile

workflows:
  version: 2
  sashay:
    jobs:
      - eslint
      - tests
      - publish:
          requires:
            - eslint
            - tests
          filters:
            branches:
              only: master

jobs:
  eslint:
    docker: *image
    steps:
      - install
      - run: make style

  tests:
    docker: *image
    steps:
      - install
      - run: make coverage-cli
      - run: make coverage-ui
      - run: bash <(curl -s https://codecov.io/bash)

  publish:
    docker: *image
    steps:
      - install
      - run: echo "//registry.npmjs.org/:_authToken=$NPMJS_TOKEN" >> ~/.npmrc
      - deploy:
          command: ./node_modules/.bin/publish
