version: 2.1

executors:
  node:
    docker:
      - image: gmathieu/node-browsers:4.0.1

commands:
  install:
    steps:
      - checkout
      - run: yarn install --frozen-lockfile

workflows:
  version: 2
  sashay:
    jobs:
      - eslint
      - npx
      - tests
      - publish:
          requires:
            - eslint
            - npx
            - tests
          filters:
            branches:
              only: master

jobs:
  eslint:
    executor: node
    steps:
      - install
      - run: make style

  npx:
    executor: node
    steps:
      - checkout
      - run: make test-npx

  tests:
    executor: node
    steps:
      - install
      - run: make coverage-cli
      - run: make coverage-ui
      - run: bash <(curl -s https://codecov.io/bash)

  publish:
    executor: node
    steps:
      - install
      - run: echo "//registry.npmjs.org/:_authToken=$NPMJS_TOKEN" >> ~/.npmrc
      - deploy:
          command: ./node_modules/.bin/publish
