version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12-browsers

commands:
  install:
    steps:
      - checkout
      - run: yarn install --frozen-lockfile

workflows:
  version: 2
  sashay:
    jobs:
      - eslint
      - npx
      - tests
      - publish:
          requires:
            - eslint
            - npx
            - tests
          filters:
            branches:
              only: master

jobs:
  eslint:
    executor: node
    steps:
      - install
      - run: make style

  npx:
    executor: node
    steps:
      - checkout
      - run: sudo npm link
      - run:
          command: npx sashay ~/project/lib/cli/__test__/fixtures/valid/index.raml -o web
          working_directory: /tmp

  tests:
    executor: node
    steps:
      - install
      - run: make coverage-cli
      - run: make coverage-ui
      - run: bash <(curl -s https://codecov.io/bash)

  publish:
    executor: node
    steps:
      - install
      - run: echo "//registry.npmjs.org/:_authToken=$NPMJS_TOKEN" >> ~/.npmrc
      - deploy:
          command: ./node_modules/.bin/publish
