#%RAML 0.8
---
baseUri: a
title: a
version: a
schemas:
  - foo: !include schemas/foo/object.json
/a:
  displayName: a
  post:
    displayName: a
    body:
      application/json:
        schema: |
          {
            "type": "object",
            "properties": {
              "a": {
                "type": "string"
              }
            }
          }
        example: |
          {
            "a": 1
          }
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "type": "object",
                "properties": {
                  "a": {
                    "type": "string"
                  }
                }
              }
            example: |
              {
                "a": "Hello"
              }
